[package]
name = "day-2024-21"
version = "0.1.0"
edition = "2021"

[dependencies]
rustlind-lib = { path = "../../lib" }
aoc-lib = { path = "../aoc-lib" }
regex = "1"
itertools = "0.11"
cached = "0.54.0"
